### ISSUE TITLE
about installation

### ISSUE THREAD

**Issue by byy666** [aidos-lab/pytorch-topological#1]
why i can't install it through pip, is there any other way to install without poetry?

**Comment by byy666** [comment]
i use python3.7, and it said "ERROR: Could not find a version that satisfies the requirement torch-topological (from versions: none)
ERROR: No matching distribution found for torch-topological"

**Comment by Pseudomanifold** [comment]
Unfortunately, `pytorch-topological` does not support this Python version. I have tested the package with Python versions `>= 3.9`. Please update your Python version or use a tool such as [`pyenv`](https://github.com/pyenv/pyenv) to manage multiple versions of Python.
