### ISSUE TITLE
run alpha_complex.py with error

### ISSUE THREAD

**Issue by amiltonwong** [aidos-lab/pytorch-topological#12]
Hi, developers,

When I run the example, `python alpha_complex.py`, I got the following error:
```
Traceback (most recent call last):
  File "/data/code13/pytorch-topological/torch_topological/examples/alpha_complex.py", line 13, in <module>
    from torch_topological.utils import SelectByDimension
ImportError: cannot import name 'SelectByDimension' from 'torch_topological.utils' (/root2/anaconda3/envs/pytorch-topological/lib/python3.9/site-packages/torch_topological/utils/__init__.py)
```

Is there something missing in the import location?

Thanks~

**Comment by Pseudomanifold** [comment]
Hi!

Might be an installation issue; did you install the code using `pip`? I'll have to update the release.

**Comment by Pseudomanifold** [comment]
Giving this a ping; can you please check whether the problem occurs with the dev version, i.e. with a clone of this repo?

**Comment by amiltonwong** [comment]
@Pseudomanifold ,
Thanks for your reply. Yes, I used pip to install the package and encounter such error. If I switch to install it from source, there's no problem in running `python alpha_complex.py`.

**Comment by Pseudomanifold** [comment]
Made a new release to fix this. Thanks for reporting it!
