### ISSUE TITLE
Does torch_topological.nn and functions like SignatureLossm, VietorisRipsComplex use GPU

### ISSUE THREAD

**Issue by prashkmr** [aidos-lab/pytorch-topological#13]
Hi,

The code and documentaiton are very fluid and easy to understand. Thanks for the code.
I wanted to know whether  torch_topological.nn  and its various functions support GPU computations(ie. do they run on GPU).
If not, is there any way to modify the code to allow them to run on GPU.

Eagerly awaiting a response.

Thanks,
Prashant

**Comment by Pseudomanifold** [comment]
Dear Prashant,

Thanks for your kind words! At the moment, the backends do not support GPU calculations. Once you have your topological features, the layers and losses run on the GPU, though.

Supporting GPUs would be possible, but requires additional implementation efforts.

Hope that helps---feel free to reopen for additional discussion.

Best,
  Bastian
