### ISSUE TITLE
About use this repo

### ISSUE THREAD

**Issue by good-demo** [aidos-lab/pytorch-topological#15]
Can I use this repo(pytorch-topological)  to build TOGL（Topological Graph Neural Networks）

**Comment by good-demo** [comment]
> Can I use this repo(pytorch-topological) to build TOGL（Topological Graph Neural Networks）

**Comment by Pseudomanifold** [comment]
With all due respect, what's this supposed to be? No, you can't use this repository to build TOGL yet. Every time you change this issue, we get email notifications...this is not accomplishing anything.
