### ISSUE TITLE
too much time-consuming after adding topology loss term(Cubical complex)

### ISSUE THREAD

**Issue by jbHu67** [aidos-lab/pytorch-topological#24]
I found that my code very slow after adding topology loss( using cubical complex). The GPU usage down to 10%, but around 90% without adding topology loss. Is it normal?

**Comment by Pseudomanifold** [comment]
I cannot answer this question without knowing more details about your code. Notice that there is currently no GPU implementation for cubical complexes, but maybe the culprit is more in the way data are being transferred?

**Comment by jbHu67** [comment]
Okay, thanks for your answer. My code of computing topological loss is almost same as the work "https://github.com/marrlab/SHAPR_torch" but is a 2D problem. I will continue check the reason.

**Comment by jbHu67** [comment]
Dear,
Thanks for your answer. My code of computing topological loss is almost same as the work "https://github.com/marrlab/SHAPR_torch" but is a 2D problem. I will continue check the reason.

**Comment by Pseudomanifold** [comment]
One thing you could try is downsample your data via one of the `interpolate` functions. I'm closing this issue for now, please reopen if you have more details about your specific problem.
