### ISSUE TITLE
About  SignatureLoss

### ISSUE THREAD

**Issue by good-demo** [aidos-lab/pytorch-topological#25]
Thank you for sharing this repo
But now I have a problem
Use this  SignatureLoss function it return 'AttributeError: 'list' object has no attribute 'pairing''

self.vr = VietorisRipsComplex(dim=0)
self.topo_loss = SignatureLoss(p=2)

a = x
pi_x = self.vr(a)
b = x
pi_z = self.vr(b)

topo_loss = self.topo_loss([a, pi_x],[b, pi_z])

**Comment by Pseudomanifold** [comment]
What's the shape of `x` in your example? What's the full trace of the error message?

**Comment by good-demo** [comment]
def forward(self, x):
        N, C, T, V, M = x.size()
        x = rearrange(x, 'n c t v m -> (n m t) v c', m=M, v=V).contiguous()
        a = x
        pi_x = self.vr(a)
       
        x = self.A_vector.to(x.float()).expand(N*M*T, -1, -1) @ x

        x = self.to_joint_embedding(x)
        x += self.pos_embedding[:, :self.num_point]
        x = rearrange(x, '(n m t) v c -> n (m v c) t', m=M, t=T).contiguous()

        x = self.data_bn(x)
        x = rearrange(x, 'n (m v c) t -> (n m) c t v', m=M, v=V).contiguous()
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.l4(x)
        x = self.l5(x)
        x = self.l6(x)
        x = self.l7(x)
        x = self.l8(x)
        x = self.l9(x)
        b = x
        b = rearrange(b, '(n m) c t v -> (n m t) v c', m=M, v=V).contiguous()
        pi_z = self.vr(b)

**Comment by good-demo** [comment]
I try to print the pi_x
dict_items([(0, [PersistenceInformation(pairing=array([[24, 24, 11],
       [22, 22,  7],
       [16, 16,  0],
       [21, 21,  7],
       [23, 23, 11],
       [11, 11, 10],
       [20, 20,  2],
       [ 7,  7,  6],
       [12, 12,  0],
       [15, 15, 14],
       [19, 19, 18],
       [ 3,  3,  2],
       [ 2, 20,  4],
       [18, 18, 15],
       [ 4, 20,  8],
       [ 0, 16, 10],
       [ 9,  9,  1],
       [17, 17, 13],
       [10, 23, 17],
       [ 8, 20,  1],
       [13, 10,  9],
       [ 5,  5,  1],
       [ 6,  6,  5],
       [14, 14, 13]]), diagram=tensor([[0.0000, 0.0277],
        [0.0000, 0.0406],
        [0.0000, 0.0518],
        [0.0000, 0.0612],
        [0.0000, 0.0657],
        [0.0000, 0.0754],
        [0.0000, 0.0762],
        [0.0000, 0.0813],
        [0.0000, 0.0834],
        [0.0000, 0.0944],
        [0.0000, 0.1168],
        [0.0000, 0.1265],
        [0.0000, 0.1393],
        [0.0000, 0.1494],
        [0.0000, 0.1506],
        [0.0000, 0.1584],
        [0.0000, 0.1764],
        [0.0000, 0.1899],
        [0.0000, 0.1978],
        [0.0000, 0.2272],
        [0.0000, 0.2369],
        [0.0000, 0.2390],
        [0.0000, 0.2396],
        [0.0000, 0.2762]], device='cuda:0'), dimension=0)])])

**Comment by Pseudomanifold** [comment]
Can you check the length of `pi_x`? Does this match your batch dimension? You might have to "unwrap" the results and calculate an individual loss for each of the components.

Can you provide details about `a.shape` and `b.shape`, respectively? Maybe something in the `VietorisRipsComplex` class does not work.

**Comment by good-demo** [comment]
I modified  'topo_loss = self.topo_loss（[a， pi_x]，[b， pi_z]）'  ' topo_loss = self.topo_loss([a, pi_x[1]],[b, pi_z[1]])'
and the program will not report an error,  I don't know if this is the correct modification

**Comment by Pseudomanifold** [comment]
Can you please provide details about `a.shape` and `b.shape`, respectively?

**Comment by good-demo** [comment]
a.shape: torch.Size([8192, 25, 3])
pi_x length: 8192
b.shape: torch.Size([2048, 25, 256])

**Comment by Pseudomanifold** [comment]
Great, thanks. I think there are two things that are unexpected here: the signature loss was not meant to handle different cardinalities of batches; you may have to iterate over all _pairs_ of `pi_x` and `pi_y` information.

However: the signature loss works best if you compare point clouds that are _paired_ with each other, i.e. you have an original point cloud `x` and an embedded point cloud `y`. I don't understand why the shapes of `a` and `b` are different in your case---are you embedding `a`?

**Comment by good-demo** [comment]
"""""
def forward(self, x):
        N, C, T, V, M = x.size()
        x = rearrange(x, 'n c t v m -> (n m t) v c', m=M, v=V).contiguous()
        a = x
        # print('a.shape:',a.shape)
        pi_x = self.vr(a)
        # print('pi_x length:',len(pi_x))
        
        x = self.A_vector.to(torch.float32).to(x.device).expand(N*M*T, -1, -1) @ x
        # x = self.A_vector.to(torch.float32).expand(N*M*T, -1, -1) @ x

        x = self.to_joint_embedding(x)
        x += self.pos_embedding[:, :self.num_point]
        x = rearrange(x, '(n m t) v c -> n (m v c) t', m=M, t=T).contiguous()
        x = self.data_bn(x)
        x = rearrange(x, 'n (m v c) t -> (n m) c t v', m=M, v=V).contiguous()
        x = self.l1(x)
        x = self.l2(x)
        x = self.l3(x)
        x = self.l4(x)
        x = self.l5(x)
        x = self.l6(x)
        x = self.l7(x)
        x = self.l8(x)
        x = self.l9(x)
        b = x
        b = rearrange(b, '(n m) c t v -> (n m t) v c', m=M, v=V).contiguous()
        # print('b.shape:',b.shape)
        pi_z = self.vr(b)
        # print('pi_z length:',len(pi_z))
        
        
        

        # N*M,C,T,V
        c_new = x.size(1)
        x = x.view(N, M, c_new, -1)
        x = x.mean(3).mean(1)
        x = F.relu(self.fc(x))
        x = self.drop_out(x)
        y_hat = self.decoder(x)
        topo_loss = self.topo_loss([a, pi_x[1]],[b, pi_z[1]])

        return y_hat, topo_loss
"""""""
Thank you for your patient reply

I referenced autoencoders.py to modify my code，and the  a is the input X and b is the latent Z

**Comment by Pseudomanifold** [comment]
I don't fully understand your code, but you should make sure that the embedding has the same number of points. Then you can use the loss by iterating over batches:


```
        topo_loss = torch.stack([
            self.topo_loss(pred_batch, latent_batch)
            for pred_batch, latent_batch in zip(pi_x, pi_y)
        ])
```

You can then continue with `topo_loss` and for instance take the mean etc. Hope that helps!

(I am closing this issue since it does not indicate a bug in `pytorch-topological`; feel free to reopen if there is a problem with the signature loss implementation, though)
