### ISSUE TITLE
support for python<3.9

### ISSUE THREAD

**Issue by sinAshish** [aidos-lab/pytorch-topological#30]
I know this is futile since upgradation is the natural flow of things. but I feel some people (like me) have a lot of other projects/envs using 3.5<=python<=3.8, so upgrading to python3.9 breaks some libraries especially when some of them support only certain versions of CUDA/torch.
It would be great if there was support for any of python3.5/6/7/8!

**Comment by Pseudomanifold** [comment]
I understand that. Have you tried doing a manual downgrade of the library requirements? You can change the version indicator in `pyproject.toml`.

**Comment by sinAshish** [comment]
thanks. it worked. just had to make sure that it didn't upgrade my other necessary torch versions

**Comment by Pseudomanifold** [comment]
Thanks a lot!

Did you have to change anything else? If so, please kindly document these changes here—I'll integrate them in the `README`. Closing this for now, please reopen with more details in case there was more to it than updating the Python version in `pyproject.toml`.

**Comment by sinAshish** [comment]
No, only the relevant torch versions had to removed, followed by `poetry lock` and then `poetry install`. 
Thanks for the prompt response!
