### ISSUE TITLE
About classification.py this repo

### ISSUE THREAD

**Issue by good-demo** [aidos-lab/pytorch-topological#33]
In classification.py  can I use  Alpha complex or Cubical complex replace Vietoris--Rips complex?

**Comment by Pseudomanifold** [comment]
Yes, sure.

**Comment by good-demo** [comment]
Thanks for your reply, but when I used it will  report an error
munmap_chunk(): invalid pointer
train.sh: line 13: 2356825 Aborted                 (core dumped) python main.py
Vietoris--Rips complex without this error

**Comment by Pseudomanifold** [comment]
Please add trace information from Python to track this issue, I don't know where this error is coming from.
