### ISSUE TITLE
scipy requirements

### ISSUE THREAD

**Issue by carrtesy** [aidos-lab/pytorch-topological#39]
Hi, thanks for the great work!

I am trying to use SignatureLoss() function, but encountering scipy issue:

`
Traceback (most recent call last):
  File "/workspace/nfsdata/home/dmkim/ProbAD/main.py", line 10, in <module>
    from models.AE import MLP_AE, MLP_TAE
  File "/workspace/nfsdata/home/dmkim/ProbAD/models/AE.py", line 38, in <module>
    from torch_topological.nn import SignatureLoss
  File "/opt/conda/envs/ProbAD/lib/python3.10/site-packages/torch_topological/nn/__init__.py", line 5, in <module>
    from .distances import WassersteinDistance
  File "/opt/conda/envs/ProbAD/lib/python3.10/site-packages/torch_topological/nn/distances.py", line 3, in <module>
    import ot
  File "/opt/conda/envs/ProbAD/lib/python3.10/site-packages/ot/__init__.py", line 24, in <module>
    from . import optim
  File "/opt/conda/envs/ProbAD/lib/python3.10/site-packages/ot/optim.py", line 23, in <module>
    from scipy.optimize.linesearch import scalar_search_armijo
ImportError: cannot import name 'scalar_search_armijo' from 'scipy.optimize.linesearch' (/opt/conda/envs/ProbAD/lib/python3.10/site-packages/scipy/optimize/linesearch.py)
`

I'm using scipy ver 1.14.0.
Are there any requirement for scipy? (need to down/up-grade my scipy?)
Telling me exact scipy ver that you use would also help.  

Thanks in advance,

carrtesy.

**Comment by Pseudomanifold** [comment]
There are no version requirements. Is it possible that this is an issue arising from POT? When you try to manually import the library, does this work?

**Comment by carrtesy** [comment]
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/4c7f78a3-735a-4483-ab7a-8900e58b0c18">
manually importing POT doesn't seem to work.

And torch-topological requires torch-topological 0.1.7 requires POT<0.9.0,>=0.8.0
<img width="360" alt="image" src="https://github.com/user-attachments/assets/37f1a9a7-4825-4f45-a15d-fad234c6ddca">


And mine is POT=0.8.0
<img width="569" alt="image" src="https://github.com/user-attachments/assets/b5e91077-b200-478f-8962-06237dec71aa">

May I ask if you see any issues here?

thanks,

carrtesy

**Comment by Pseudomanifold** [comment]
This seems to be a problem with POT. Can you change the requirements to allow a new version to be used?

**Comment by carrtesy** [comment]
I'd try other POT versions then, thanks!

**Comment by Pseudomanifold** [comment]
There's nothing to solve here, unfortunately. If you get an error raised by POT, then POT needs updating.

**Comment by dashangyanhua** [comment]
> 不幸的是，这里没有什么需要解决的。如果收到 POT 引发的错误，则 POT 需要更新。

Thank you for your quick response！ I found that the python version was the cause of the problem. When I changed to python=3.9,  and re-installed the torch_topological,  I solved the problem. So do other versions of python have some unexpected problems?

**Comment by Pseudomanifold** [comment]
It's more of a problem of incompatibilities between downstream packages. Some of these issues are beyond our control, unfortunately.
