### ISSUE TITLE
About torch_topological Library Installation

### ISSUE THREAD

**Issue by Arginonn** [aidos-lab/pytorch-topological#42]
Hello, thank you very much for providing the torch_topological library. During installation, I found that only versions with torch>=1.10.1 are supported. Is there any other way to install torch versions lower than 1.10.1? Thank you very much for your reply.
![image](https://github.com/user-attachments/assets/7b4c3a80-c70f-488b-9d20-1d63c8a8a035)

**Comment by Pseudomanifold** [comment]
You can certainly try it out but I don't know the ramifications of using older versions. Good luck!
